//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_data_source_filter_descriptor_demo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Context for the RIA application.
    /// </summary>
    /// <remarks>
    /// This context extends the base to make application services and types available
    /// for consumption from code and xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the WebContext class.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the context that is registered as a lifetime object with the current application.
        /// </summary>
        /// <exception cref="InvalidOperationException"> is thrown if there is no current application,
        /// no contexts have been added, or more than one context has been added.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
namespace domain_data_source_filter_descriptor_demo.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.ServiceModel.Web;
    
    
    /// <summary>
    /// The 'SM' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/domain_data_source_filter_descriptor_demo" +
        ".Web")]
    public sealed partial class SM : Entity
    {
        
        private int _id;
        
        private string _message;
        
        private Nullable<DateTime> _time;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void OnmessageChanging(string value);
        partial void OnmessageChanged();
        partial void OntimeChanging(Nullable<DateTime> value);
        partial void OntimeChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SM"/> class.
        /// </summary>
        public SM()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'id' value.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.ValidateProperty("id", value);
                    this._id = value;
                    this.RaisePropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'message' value.
        /// </summary>
        [DataMember()]
        [StringLength(50)]
        public string message
        {
            get
            {
                return this._message;
            }
            set
            {
                if ((this._message != value))
                {
                    this.OnmessageChanging(value);
                    this.RaiseDataMemberChanging("message");
                    this.ValidateProperty("message", value);
                    this._message = value;
                    this.RaiseDataMemberChanged("message");
                    this.OnmessageChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'time' value.
        /// </summary>
        [DataMember()]
        public Nullable<DateTime> time
        {
            get
            {
                return this._time;
            }
            set
            {
                if ((this._time != value))
                {
                    this.OntimeChanging(value);
                    this.RaiseDataMemberChanging("time");
                    this.ValidateProperty("time", value);
                    this._time = value;
                    this.RaiseDataMemberChanged("time");
                    this.OntimeChanged();
                }
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._id;
        }
    }
    
    /// <summary>
    /// The DomainContext corresponding to the 'SMSDomainService' DomainService.
    /// </summary>
    public sealed partial class SMSDomainContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SMSDomainContext"/> class.
        /// </summary>
        public SMSDomainContext() : 
                this(new WebDomainClient<ISMSDomainServiceContract>(new Uri("domain_data_source_filter_descriptor_demo-Web-SMSDomainService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SMSDomainContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The SMSDomainService service URI.</param>
        public SMSDomainContext(Uri serviceUri) : 
                this(new WebDomainClient<ISMSDomainServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SMSDomainContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public SMSDomainContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="SM"/> entity instances that have been loaded into this <see cref="SMSDomainContext"/> instance.
        /// </summary>
        public EntitySet<SM> SMs
        {
            get
            {
                return base.EntityContainer.GetEntitySet<SM>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="SM"/> entity instances using the 'GetSMS' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="SM"/> entity instances.</returns>
        public EntityQuery<SM> GetSMSQuery()
        {
            this.ValidateMethod("GetSMSQuery", null);
            return base.CreateQuery<SM>("GetSMS", null, false, true);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new SMSDomainContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'SMSDomainService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface ISMSDomainServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetSMS' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/SMSDomainService/GetSMSDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/SMSDomainService/GetSMS", ReplyAction="http://tempuri.org/SMSDomainService/GetSMSResponse")]
            [WebGet()]
            IAsyncResult BeginGetSMS(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetSMS'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetSMS'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetSMS' operation.</returns>
            QueryResult<SM> EndGetSMS(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'SubmitChanges' operation.
            /// </summary>
            /// <param name="changeSet">The change-set to submit.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/SMSDomainService/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/SMSDomainService/SubmitChanges", ReplyAction="http://tempuri.org/SMSDomainService/SubmitChangesResponse")]
            IAsyncResult BeginSubmitChanges(IEnumerable<ChangeSetEntry> changeSet, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginSubmitChanges'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginSubmitChanges'.</param>
            /// <returns>The collection of change-set entry elements returned from 'SubmitChanges'.</returns>
            IEnumerable<ChangeSetEntry> EndSubmitChanges(IAsyncResult result);
        }
        
        internal sealed class SMSDomainContextEntityContainer : EntityContainer
        {
            
            public SMSDomainContextEntityContainer()
            {
                this.CreateEntitySet<SM>(EntitySetOperations.All);
            }
        }
    }
}
