//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace domain_service_auto_refresh_demo.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CountEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CountEntities object using the connection string found in the 'CountEntities' section of the application configuration file.
        /// </summary>
        public CountEntities() : base("name=CountEntities", "CountEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CountEntities object.
        /// </summary>
        public CountEntities(string connectionString) : base(connectionString, "CountEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CountEntities object.
        /// </summary>
        public CountEntities(EntityConnection connection) : base(connection, "CountEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Count> Counts
        {
            get
            {
                if ((_Counts == null))
                {
                    _Counts = base.CreateObjectSet<Count>("Counts");
                }
                return _Counts;
            }
        }
        private ObjectSet<Count> _Counts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Counts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCounts(Count count)
        {
            base.AddObject("Counts", count);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CountModel", Name="Count")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Count : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Count object.
        /// </summary>
        /// <param name="value">Initial value of the value property.</param>
        public static Count CreateCount(global::System.Int32 value)
        {
            Count count = new Count();
            count.value = value;
            return count;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 value
        {
            get
            {
                return _value;
            }
            set
            {
                if (_value != value)
                {
                    OnvalueChanging(value);
                    ReportPropertyChanging("value");
                    _value = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("value");
                    OnvalueChanged();
                }
            }
        }
        private global::System.Int32 _value;
        partial void OnvalueChanging(global::System.Int32 value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();

        #endregion
    
    }

    #endregion
    
}
