//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datagrid_raidobutton_demo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Context for the RIA application.
    /// </summary>
    /// <remarks>
    /// This context extends the base to make application services and types available
    /// for consumption from code and xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the WebContext class.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the context that is registered as a lifetime object with the current application.
        /// </summary>
        /// <exception cref="InvalidOperationException"> is thrown if there is no current application,
        /// no contexts have been added, or more than one context has been added.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
namespace datagrid_raidobutton_demo.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.ServiceModel.Web;
    
    
    /// <summary>
    /// The 'Book' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/datagrid_raidobutton_demo.Web")]
    public sealed partial class Book : Entity
    {
        
        private int _id;
        
        private string _isbn;
        
        private string _name;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnIsbnChanging(string value);
        partial void OnIsbnChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Book"/> class.
        /// </summary>
        public Book()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Id' value.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnIdChanging(value);
                    this.ValidateProperty("Id", value);
                    this._id = value;
                    this.RaisePropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Isbn' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(25)]
        public string Isbn
        {
            get
            {
                return this._isbn;
            }
            set
            {
                if ((this._isbn != value))
                {
                    this.OnIsbnChanging(value);
                    this.RaiseDataMemberChanging("Isbn");
                    this.ValidateProperty("Isbn", value);
                    this._isbn = value;
                    this.RaiseDataMemberChanged("Isbn");
                    this.OnIsbnChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Name' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(50)]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    this.OnNameChanging(value);
                    this.RaiseDataMemberChanging("Name");
                    this.ValidateProperty("Name", value);
                    this._name = value;
                    this.RaiseDataMemberChanged("Name");
                    this.OnNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._id;
        }
    }
    
    /// <summary>
    /// The DomainContext corresponding to the 'LibraryDomainService' DomainService.
    /// </summary>
    public sealed partial class LibraryDomainContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LibraryDomainContext"/> class.
        /// </summary>
        public LibraryDomainContext() : 
                this(new WebDomainClient<ILibraryDomainServiceContract>(new Uri("datagrid_raidobutton_demo-Web-LibraryDomainService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LibraryDomainContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The LibraryDomainService service URI.</param>
        public LibraryDomainContext(Uri serviceUri) : 
                this(new WebDomainClient<ILibraryDomainServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LibraryDomainContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public LibraryDomainContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="Book"/> entity instances that have been loaded into this <see cref="LibraryDomainContext"/> instance.
        /// </summary>
        public EntitySet<Book> Books
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Book>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Book"/> entity instances using the 'GetBooks' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Book"/> entity instances.</returns>
        public EntityQuery<Book> GetBooksQuery()
        {
            this.ValidateMethod("GetBooksQuery", null);
            return base.CreateQuery<Book>("GetBooks", null, false, true);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new LibraryDomainContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'LibraryDomainService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface ILibraryDomainServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetBooks' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/LibraryDomainService/GetBooksDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/LibraryDomainService/GetBooks", ReplyAction="http://tempuri.org/LibraryDomainService/GetBooksResponse")]
            [WebGet()]
            IAsyncResult BeginGetBooks(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetBooks'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetBooks'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetBooks' operation.</returns>
            QueryResult<Book> EndGetBooks(IAsyncResult result);
        }
        
        internal sealed class LibraryDomainContextEntityContainer : EntityContainer
        {
            
            public LibraryDomainContextEntityContainer()
            {
                this.CreateEntitySet<Book>(EntitySetOperations.None);
            }
        }
    }
}
