//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace autocomplete_custom_searchmode_demo.PersonService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    public partial class Person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FirstNameField;
        
        private string SecondNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonService.PersonServiceSoap")]
    public interface PersonServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetPersons", ReplyAction="*")]
        System.IAsyncResult BeginGetPersons(autocomplete_custom_searchmode_demo.PersonService.GetPersonsRequest request, System.AsyncCallback callback, object asyncState);
        
        autocomplete_custom_searchmode_demo.PersonService.GetPersonsResponse EndGetPersons(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersons", Namespace="http://tempuri.org/", Order=0)]
        public autocomplete_custom_searchmode_demo.PersonService.GetPersonsRequestBody Body;
        
        public GetPersonsRequest() {
        }
        
        public GetPersonsRequest(autocomplete_custom_searchmode_demo.PersonService.GetPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPersonsRequestBody {
        
        public GetPersonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonsResponse", Namespace="http://tempuri.org/", Order=0)]
        public autocomplete_custom_searchmode_demo.PersonService.GetPersonsResponseBody Body;
        
        public GetPersonsResponse() {
        }
        
        public GetPersonsResponse(autocomplete_custom_searchmode_demo.PersonService.GetPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<autocomplete_custom_searchmode_demo.PersonService.Person> GetPersonsResult;
        
        public GetPersonsResponseBody() {
        }
        
        public GetPersonsResponseBody(System.Collections.ObjectModel.ObservableCollection<autocomplete_custom_searchmode_demo.PersonService.Person> GetPersonsResult) {
            this.GetPersonsResult = GetPersonsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonServiceSoapChannel : autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPersonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<autocomplete_custom_searchmode_demo.PersonService.Person> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<autocomplete_custom_searchmode_demo.PersonService.Person>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceSoapClient : System.ServiceModel.ClientBase<autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap>, autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap {
        
        private BeginOperationDelegate onBeginGetPersonsDelegate;
        
        private EndOperationDelegate onEndGetPersonsDelegate;
        
        private System.Threading.SendOrPostCallback onGetPersonsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PersonServiceSoapClient() {
        }
        
        public PersonServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetPersonsCompletedEventArgs> GetPersonsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap.BeginGetPersons(autocomplete_custom_searchmode_demo.PersonService.GetPersonsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPersons(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetPersons(System.AsyncCallback callback, object asyncState) {
            autocomplete_custom_searchmode_demo.PersonService.GetPersonsRequest inValue = new autocomplete_custom_searchmode_demo.PersonService.GetPersonsRequest();
            inValue.Body = new autocomplete_custom_searchmode_demo.PersonService.GetPersonsRequestBody();
            return ((autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap)(this)).BeginGetPersons(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        autocomplete_custom_searchmode_demo.PersonService.GetPersonsResponse autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap.EndGetPersons(System.IAsyncResult result) {
            return base.Channel.EndGetPersons(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<autocomplete_custom_searchmode_demo.PersonService.Person> EndGetPersons(System.IAsyncResult result) {
            autocomplete_custom_searchmode_demo.PersonService.GetPersonsResponse retVal = ((autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap)(this)).EndGetPersons(result);
            return retVal.Body.GetPersonsResult;
        }
        
        private System.IAsyncResult OnBeginGetPersons(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetPersons(callback, asyncState);
        }
        
        private object[] OnEndGetPersons(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<autocomplete_custom_searchmode_demo.PersonService.Person> retVal = this.EndGetPersons(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPersonsCompleted(object state) {
            if ((this.GetPersonsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPersonsCompleted(this, new GetPersonsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPersonsAsync() {
            this.GetPersonsAsync(null);
        }
        
        public void GetPersonsAsync(object userState) {
            if ((this.onBeginGetPersonsDelegate == null)) {
                this.onBeginGetPersonsDelegate = new BeginOperationDelegate(this.OnBeginGetPersons);
            }
            if ((this.onEndGetPersonsDelegate == null)) {
                this.onEndGetPersonsDelegate = new EndOperationDelegate(this.OnEndGetPersons);
            }
            if ((this.onGetPersonsCompletedDelegate == null)) {
                this.onGetPersonsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPersonsCompleted);
            }
            base.InvokeAsync(this.onBeginGetPersonsDelegate, null, this.onEndGetPersonsDelegate, this.onGetPersonsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap CreateChannel() {
            return new PersonServiceSoapClientChannel(this);
        }
        
        private class PersonServiceSoapClientChannel : ChannelBase<autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap>, autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap {
            
            public PersonServiceSoapClientChannel(System.ServiceModel.ClientBase<autocomplete_custom_searchmode_demo.PersonService.PersonServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPersons(autocomplete_custom_searchmode_demo.PersonService.GetPersonsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetPersons", _args, callback, asyncState);
                return _result;
            }
            
            public autocomplete_custom_searchmode_demo.PersonService.GetPersonsResponse EndGetPersons(System.IAsyncResult result) {
                object[] _args = new object[0];
                autocomplete_custom_searchmode_demo.PersonService.GetPersonsResponse _result = ((autocomplete_custom_searchmode_demo.PersonService.GetPersonsResponse)(base.EndInvoke("GetPersons", _args, result)));
                return _result;
            }
        }
    }
}
